<Project>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
  <PropertyGroup Condition="'$(MSBuildProjectName)' == 'TrumpLab.Core'">
    <BaseOutputPath>$(MSBuildThisFileDirectory)bin/TrumpLab.Core/</BaseOutputPath>
    <BaseIntermediateOutputPath>$(MSBuildThisFileDirectory)obj/TrumpLab.Core/</BaseIntermediateOutputPath>
  </PropertyGroup>
</Project>
